---
- name: Check Galera Cluster Status
  hosts: role_database
  become: true
  vars_files:
    - ../group_vars/all.yml
    - ../group_vars/vault.yml
  tasks:
    - name: Install Python MySQL package
      apt:
        name: python3-mysqldb
        state: present

    - name: Get Galera cluster status
      community.mysql.mysql_query:
        login_user: root
        login_password: "{{ mysql_root_password }}"
        login_unix_socket: /var/run/mysqld/mysqld.sock
        query: SHOW STATUS LIKE 'wsrep_%'
      register: galera_status
      ignore_errors: true

    - name: Display cluster size and status
      debug:
        msg: |
          Node: {{ inventory_hostname }}
          Cluster Size: {{ galera_status.query_result[0] | selectattr('Variable_name', 'eq', 'wsrep_cluster_size') | map(attribute='Value') | first }}
          Cluster Status: {{ galera_status.query_result[0] | selectattr('Variable_name', 'eq', 'wsrep_cluster_status') | map(attribute='Value') | first }}
          Node State: {{ galera_status.query_result[0] | selectattr('Variable_name', 'eq', 'wsrep_local_state_comment') | map(attribute='Value') | first }}
          Connected: {{ galera_status.query_result[0] | selectattr('Variable_name', 'eq', 'wsrep_connected') | map(attribute='Value') | first }}
          Ready: {{ galera_status.query_result[0] | selectattr('Variable_name', 'eq', 'wsrep_ready') | map(attribute='Value') | first }}